import type {CreateAbstractsConfig} from "@tinloof/sanity-extends";
import type * as React from "react";
import type {DocumentPluginOptions, SchemaPluginOptions} from "sanity";
import type {
	ListItemBuilder,
	StructureBuilder,
	StructureResolverContext,
	StructureToolOptions,
	View,
	ViewBuilder,
} from "sanity/structure";

/**
 * Locale configuration for i18n
 * @public
 */
export type Locale = {
	id: Intl.UnicodeBCP47LocaleIdentifier;
	title: string;
};

/**
 * Structure tool options managed by the document options plugin.
 * @public
 */
export type DocumentOptionsStructureOptions = Pick<
	StructureToolOptions,
	"keepPanesOnCreate"
> & {
	locales?: Locale[];
	/** Document types to omit from the autogenerated structure. */
	hide?: string[];
	toolTitle?: string;
	localeFieldName?: string;
};

/**
 * Main plugin options
 * @public
 */
export type DocumentOptionsPluginOptions = {
	/** Configure the generated structure tool, or disable the tool with false. */
	structure?: DocumentOptionsStructureOptions | false;
	abstracts?: CreateAbstractsConfig<"singleton" | "sync" | "orderable">;
};

/**
 * Compatibility alias for DocumentOptionsStructureOptions.
 * @public
 */
export type InlineStructureProps = DocumentOptionsStructureOptions;

/**
 * Compatibility alias for DocumentOptionsPluginOptions.
 * @public
 */
export type DocumentOptionsProps = DocumentOptionsPluginOptions;

/**
 * Common structure options
 * @public
 */
export type CommonStructureOptions = {
	icon?: React.ComponentType | React.ReactNode;
	title?: string;
	views?: (S: StructureBuilder) => (View | ViewBuilder)[];
};

/**
 * Built-in structure options
 * @public
 */
export type StructureBuiltinOptions =
	| ({
			singleton:
				| true
				| {
						id?: string;
				  };
	  } & CommonStructureOptions)
	| ({
			// Case 2: non-singleton (or omitted)
			singleton?: false | undefined;
			orderable?: boolean;
	  } & CommonStructureOptions);

declare module "sanity" {
	interface DocumentOptions {
		document?: {
			newDocumentOptions?: DocumentPluginOptions["newDocumentOptions"];
			actions?: DocumentPluginOptions["actions"];
			badges?: DocumentPluginOptions["badges"];
		};
		schema?: {
			templates?: SchemaPluginOptions["templates"];
		};
		structureGroup?: string | string[];
		/** Set to false to omit this type from autogenerated structure only. */
		structureOptions?:
			| false
			| StructureBuiltinOptions
			| ((
					S: StructureBuilder,
					context: StructureResolverContext,
			  ) => ListItemBuilder);
		localized?: boolean;
	}
}

declare module "sanity" {
	interface NewDocumentOptionsContext {
		schemaType: string;
	}
}

declare module "@tinloof/sanity-extends" {
	interface ExtendsRegistry {
		singleton: {
			id?: string;
		};
		orderable: undefined;
		sync: undefined;
	}
}
