import type {Metadata} from "next";
import "./globals.css";
import ExitPreview from "@tinloof/sanity-next/components/exit-preview";
import {disableDraftMode} from "@tinloof/sanity-next/actions/disable-draft-mode";
import {draftMode} from "next/headers";
import {VisualEditing} from "next-sanity/visual-editing";
import sanity from "@/lib/sanity";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
        {(await draftMode()).isEnabled && (
          <>
            <VisualEditing />
            <ExitPreview disableDraftMode={disableDraftMode} />
          </>
        )}
        <sanity.SanityLive refreshOnFocus={false} />
      </body>
    </html>
  );
}
