// PagePayload used to be hand-written here and had drifted from the schema — it
// declared `pathname: string` where the schema has a slug object. Query result
// types now come from `sanity.types.ts`, generated by `pnpm typegen`.

export interface PageProps<
	TParams extends string = never,
	TSearchParams extends string = never,
> {
	params: Promise<
		UnionToIntersection<
			{
				[K in TParams]: {
					[F in K extends `...${infer U}` ? U : K]: K extends `...${string}`
						? string[]
						: string;
				};
			}[TParams]
		>
	>;
	searchParams: Promise<{[K in TSearchParams]?: string | string[]}>;
}

export type Prettify<T> = object & {
	[K in keyof T]: T[K];
};

export type UnionToIntersection<T> = Prettify<
	(T extends any ? (x: T) => any : never) extends (x: infer R) => any
		? R
		: never
>;
