import assert from "node:assert/strict";
import test from "node:test";
import {withExtends} from "@tinloof/sanity-extends";
import {createSchema} from "sanity";
import {createStructureBuilder, structureTool} from "sanity/structure";
import {documentOptions} from "../dist/index.js";

const doc = (name, options) => ({
	name,
	type: "document",
	fields: [{name: "title", type: "string"}],
	...(options && {options}),
});
const locales = [
	{id: "en", title: "English"},
	{id: "fr", title: "French"},
];

function setup(types, structure) {
	const plugin = documentOptions({structure});
	const resolved = withExtends(types)(plugin.schema.types);
	const schema = createSchema({name: "test", types: resolved});
	const writes = [];
	const source = {
		schema,
		projectId: "test",
		dataset: "test",
		getClient: () => ({
			createIfNotExists: (value) => {
				writes.push(value);
				return Promise.resolve(value);
			},
		}),
		i18n: {t: (key) => key},
		document: {resolveNewDocumentOptions: () => []},
		templates: resolved.flatMap(({name}) =>
			[name, ...locales.map(({id}) => `${name}-${id}`)].map((id) => ({
				id,
				schemaType: name,
				title: id,
				value: {},
			})),
		),
	};
	const tool = plugin.plugins[0].tools[0];
	const S = createStructureBuilder({
		source,
		defaultDocumentNode: tool.options.defaultDocumentNode,
	});
	const context = {...source, documentStore: {}};
	const root = () => tool.options.structure(S, context)(S, context).serialize();
	return {plugin, schema, source, S, context, root, writes};
}

const titles = (items) => items.map((item) => item.title);

test("false omits only the autogenerated item; omitted, empty object and callback still work", () => {
	let callbackContext;
	const {root, context} = setup([
		doc("article", {structureOptions: false}),
		doc("post"),
		doc("category", {structureOptions: {}}),
		doc("product", {structureOptions: {title: "Entry"}}),
		doc("framework", {
			structureOptions: (S, ctx) => {
				callbackContext = ctx;
				return S.listItem()
					.title("Collections")
					.child(S.documentTypeList("article"));
			},
		}),
	]);
	const items = root().items;
	assert.deepEqual(titles(items), [
		"Posts",
		"Categories",
		"Entries",
		"Collections",
	]);
	assert.equal(callbackContext, context);
	assert.equal(items[3].child.schemaTypeName, "article");
});

test("hidden-only nested groups disappear and mixed groups keep their existing order", () => {
	const {root} = setup(
		[
			doc("hidden", {
				structureOptions: false,
				structureGroup: ["content", "empty"],
			}),
			doc("root"),
			doc("post", {structureGroup: ["content", "news"]}),
			doc("global", {structureGroup: ["empty", "nested"]}),
			doc("article", {structureGroup: ["content", "news"]}),
			doc("ungrouped", {structureGroup: [""]}),
		],
		{hide: ["global"]},
	);
	const items = root().items;
	assert.deepEqual(titles(items), ["Content", "Roots", "Ungroupeds"]);
	assert.deepEqual(titles(items[0].child.items), ["News"]);
	assert.deepEqual(titles(items[0].child.items[0].child.items), [
		"Posts",
		"Articles",
	]);
});

test("all hidden schemas produce an empty root instead of falling back to defaults", () => {
	const {root} = setup([
		doc("article", {
			structureOptions: false,
			structureGroup: ["content", "articles"],
		}),
		doc("post", {structureOptions: false}),
	]);
	assert.deepEqual(root().items, []);
});

test("global hide still takes precedence over custom callbacks and built-in options", () => {
	const {root} = setup(
		[
			doc("custom", {
				structureOptions: () => {
					throw new Error("Hidden callback ran");
				},
			}),
			doc("home", {structureOptions: {singleton: true}}),
			doc("post"),
		],
		{hide: ["custom", "home"]},
	);
	assert.deepEqual(titles(root().items), ["Posts"]);
});

test("hidden localized schemas do not require locales or generate locale groups", () => {
	const {root, writes} = setup(
		[
			doc("article", {
				localized: true,
				structureOptions: false,
				structureGroup: "content",
			}),
			doc("post", {localized: true}),
		],
		{hide: ["post"]},
	);
	assert.deepEqual(root().items, []);
	assert.deepEqual(writes, []);
	assert.throws(
		() => setup([doc("post", {localized: true})]).root(),
		/no locales/,
	);
});

test("visible localized lists preserve their filters, templates and group", () => {
	const {root} = setup(
		[
			doc("hidden", {
				localized: true,
				structureOptions: false,
				structureGroup: "content",
			}),
			doc("post", {localized: true, structureGroup: "content"}),
		],
		{locales, localeFieldName: "language"},
	);
	const group = root().items[0];
	assert.equal(group.title, "Content");
	assert.deepEqual(titles(group.child.items), ["Posts"]);
	const english = group.child.items[0].child.items[2];
	assert.equal(
		english.child.options.filter,
		"_type == $name && language == $locale",
	);
	assert.deepEqual(english.child.options.params, {name: "post", locale: "en"});
	assert.equal(english.child.initialValueTemplates[0].templateId, "post-en");
});

test("built-in singleton IDs and localized singleton entries are unchanged", () => {
	const {root, writes} = setup(
		[
			doc("home", {structureOptions: {singleton: true}}),
			doc("settings", {structureOptions: {singleton: {id: "site-settings"}}}),
			doc("landing", {
				localized: true,
				structureOptions: {singleton: {id: "site-landing"}},
			}),
		],
		{locales},
	);
	const items = root().items;
	assert.equal(items[0].child.options.id, "home");
	assert.equal(items[1].child.options.id, "site-settings");
	assert.deepEqual(
		items[2].child.items.map((item) => item.child.options.id),
		["site-landing_en", "site-landing_fr"],
	);
	assert.equal(writes.length, 1);
});

test("false overrides inherited structure options without removing orderable fields or singleton restrictions", () => {
	const {root, schema, plugin, context, writes} = setup([
		{...doc("article", {structureOptions: false}), extends: "orderable"},
		{
			...doc("home", {structureOptions: false, localized: true}),
			extends: "singleton",
		},
	]);
	assert.deepEqual(root().items, []);
	assert.ok(
		schema.get("article").fields.some((field) => field.name === "orderRank"),
	);
	assert.deepEqual(writes, []);
	const templates = [
		{id: "home", schemaType: "home"},
		{id: "article", schemaType: "article"},
	];
	assert.deepEqual(plugin.schema.templates(templates, context), [templates[1]]);
	const items = [{templateId: "home"}, {templateId: "article"}];
	for (const type of ["global", "structure", "document"]) {
		assert.deepEqual(
			plugin.document.newDocumentOptions(items, {
				...context,
				creationContext: {type},
			}),
			[items[1]],
		);
	}
	const actions = ["publish", "delete", "duplicate", "unpublish"].map(
		(action) => Object.assign(() => null, {action}),
	);
	assert.deepEqual(
		plugin.document.actions(actions, {...context, schemaType: "home"}),
		[actions[0]],
	);
});

test("hidden schemas retain references, contextual lists, templates, creation and default document views", () => {
	const template = {
		id: "article-in-framework",
		title: "Article in framework",
		schemaType: "article",
		parameters: [{name: "frameworkId", type: "string"}],
		value: ({frameworkId}) => ({
			framework: {_type: "reference", _ref: frameworkId},
		}),
	};
	const {root, schema, S, context, plugin} = setup([
		doc("article", {structureOptions: false, schema: {templates: [template]}}),
		{
			...doc("framework"),
			fields: [{name: "article", type: "reference", to: [{type: "article"}]}],
		},
	]);
	assert.deepEqual(titles(root().items), ["Frameworks"]);
	assert.equal(schema.get("article").name, "article");
	assert.equal(schema.get("framework").fields[0].type.to[0].name, "article");
	assert.equal(
		S.documentTypeList("article").serialize().schemaTypeName,
		"article",
	);
	const defaultTemplate = {
		id: "article",
		schemaType: "article",
		title: "Article",
		value: {},
	};
	assert.deepEqual(plugin.schema.templates([defaultTemplate], context), [
		defaultTemplate,
		template,
	]);
	assert.deepEqual(template.value({frameworkId: "framework-1"}), {
		framework: {_type: "reference", _ref: "framework-1"},
	});
	const items = [{templateId: "article"}, {templateId: template.id}];
	for (const type of ["global", "structure", "document"]) {
		assert.equal(
			plugin.document.newDocumentOptions(items, {
				...context,
				creationContext: {type},
			}),
			items,
		);
	}
	assert.equal(
		S.defaultDocument({schemaType: "article"}).serialize().views[0].type,
		"form",
	);
});

for (const value of [undefined, false, true]) {
	test(`keepPanesOnCreate forwards ${value} to Sanity unchanged`, () => {
		const structure = value === undefined ? {} : {keepPanesOnCreate: value};
		const tool = documentOptions({structure}).plugins[0].tools[0];
		assert.equal(tool.options.keepPanesOnCreate, value);
		const native = structureTool(structure).tools[0];
		const params = {
			type: "article",
			id: "new-article",
			template: "article-in-framework",
		};
		const payload = {frameworkId: "framework-1"};
		assert.deepEqual(
			tool.getIntentState("create", params, {}, payload),
			native.getIntentState("create", params, {}, payload),
		);
	});
}

test("omitting plugin options preserves Sanity defaults and structure false disables the tool", () => {
	assert.equal(
		documentOptions().plugins[0].tools[0].options.keepPanesOnCreate,
		undefined,
	);
	const plugin = documentOptions({structure: false});
	assert.equal(plugin.plugins, undefined);
	assert.equal(typeof plugin.document.newDocumentOptions, "function");
	assert.equal(typeof plugin.schema.templates, "function");
});

test("visible orderable documents preserve their component and locale filters", () => {
	const {root} = setup(
		[
			doc("category", {structureOptions: {orderable: true}}),
			doc("article", {localized: true, structureOptions: {orderable: true}}),
		],
		{locales, localeFieldName: "language"},
	);
	const items = root().items;
	assert.equal(items[0].title, "Categories");
	assert.equal(items[0].child.type, "component");
	assert.equal(items[0].child.options.type, "category");
	const english = items[1].child.items[0];
	assert.equal(
		english.child.options.filter,
		"_type == $type && language == $locale",
	);
	assert.deepEqual(english.child.options.params, {
		type: "article",
		locale: "en",
	});
});

test("object-form custom views still extend the default form view", () => {
	const {S} = setup([
		doc("page", {
			structureOptions: {
				views: (builder) => [
					builder.view
						.component(() => null)
						.id("preview")
						.title("Preview"),
				],
			},
		}),
	]);
	assert.deepEqual(
		S.defaultDocument({schemaType: "page"})
			.serialize()
			.views.map(({id}) => id),
		["editor", "preview"],
	);
});
